----------------------------------------------------------------
Mon May 06 13:02:13 CEST 2019:
 Iniciando instancia a816c00e-016a-8cce-edfb-000004de76d8 de Derby, versi√≥n The Apache Software Foundation - Apache Derby - 10.10.2.0 - (1582446): 
en el directorio de base de datos C:\Users\josemanuel\Desktop\nano programacion\Proyecto BaseDatos\TiendaInformatica\TiendaInformatica_Datos con el cargador de clases sun.misc.Launcher$AppClassLoader@6f94fa3e
Cargado desde file:/C:/Program%20Files/glassfish-4.1.1/javadb/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_181-b13
user.dir=C:\Users\josemanuel\Desktop\nano programacion\Proyecto BaseDatos\TiendaInformatica
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=null
Cargador de clases de base de datos iniciado - derby.database.classpath=''
Mon May 06 13:02:29 CEST 2019 Thread[main,5,main] Cleanup action starting
java.sql.SQLException: No se ha encontrado la base de datos 'TiendaInformatica'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at tiendainformatica.TiendaInformatica.main(TiendaInformatica.java:82)
Caused by: java.sql.SQLException: No se ha encontrado la base de datos 'TiendaInformatica'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 15 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: No se ha encontrado la base de datos 'TiendaInformatica'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at tiendainformatica.TiendaInformatica.main(TiendaInformatica.java:82)
============= end nested exception, level (1) ===========
Cleanup action completed
